[tool.poetry]
name = "pySigma-pipeline-wintap"
version = "0.1.0"
description = "Pipeline for working with Wintap data"
authors = ["Lindsey Whitehurst <whitehurst1@llnl.gov>"]
license = "MIT"
repository = "https://github.com/LLNL/pySigma-pipeline-wintap"
packages = [
    { include = "sigma" }
]


[tool.poetry.dependencies]
python = "^3.10"
pysigma = "^0.11.14"
black = "^24.3.0"
pysigma-backend-duckdb = {git = "https://github.com/LLNL/pySigma-backend-duckdb.git", rev = "main"}

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pytest-cov = "^4.1.0"
coverage = "^7.3.2"
isort = "^5.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
include = '\.pyi?$'

[tool.isort]
line_length = 100
profile = "black"
