name: Test
on:
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ 'ubuntu-20.04' ]
        python-version: [ '3.10', '3.11' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run:  pipx install poetry
      # Note: If the setup-python version does not match the version specified in pyproject.toml and 
      # python version in pyproject.toml is less than the runner's python version, poetry install 
      # will default to using the runner's Python version.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install
      - name: Run lint
        run: poetry run black --check . &&  poetry run isort --check-only .
      - name: Run tests
        run: poetry run pytest -vv
